### ISSUE TITLE
Missing file in src?

### ISSUE THREAD

**Issue by snpushpi** [AlexandrePsq/main_tutorial#2]
Hi, 
In the notebooks folder, I am trying to run the notebook. It imports functions from a module that doesn't exist. 
`from src.data import load_fmri_data, load_stmuli, fetch_masker`. For example in here, `load_fmri_data` doesn't exist in data.py file. Would you kindly update the github repo, please? Thanks for your great work.

**Comment by snpushpi** [comment]
ping!

**Comment by AlexandrePsq** [comment]
Hello,
I added the `process_fmri_data` function.
The functions `load_fmri_data`, `load_stmuli` should just load the paths to the files. It depends on your architecture and where you stored the files, so you can customize it depending on what you want.
The `preprocess_stimuli_data` just load the csv files.
Best,
